### We'll use this notebook to understand the actual SEC data before putting logic into our application.

In [40]:
import sys
from pathlib import Path

import pandas as pd
import json

# Project root
PROJECT_ROOT = Path.cwd().parent

# Add project root to Python path
sys.path.insert(0, str(PROJECT_ROOT))

# Import project modules
from src.ingestion.sec_client import SECClient
from src.ingestion.sec_parser import SECParser
from src.ingestion.financial_metrics import METRIC_TAGS
from src.analysis.financial_analysis import FinancialAnalyzer
from src.ingestion.company_lookup import CompanyLookup

In [41]:
client = SECClient()

In [42]:
APPLE_CIK = "320193"

In [43]:
company_facts = client.get_company_facts(APPLE_CIK)

In [44]:
company_facts.keys()

dict_keys(['cik', 'entityName', 'facts'])

In [45]:
us_gaap = company_facts["facts"]["us-gaap"]

In [46]:
for metric, tags in METRIC_TAGS.items():

    print(f"\n{metric.upper()}")

    for tag in tags:

        if tag in us_gaap:
            print(f"  ✓ {tag}")
        else:
            print(f"  ✗ {tag}")

REVENUE
  ✓ RevenueFromContractWithCustomerExcludingAssessedTax
  ✓ Revenues
  ✓ SalesRevenueNet

NET_INCOME
  ✓ NetIncomeLoss

ASSETS
  ✓ Assets

LIABILITIES
  ✓ Liabilities

CASH
  ✓ CashAndCashEquivalentsAtCarryingValue

OPERATING_CASH_FLOW
  ✓ NetCashProvidedByUsedInOperatingActivities

In [47]:
parser = SECParser()

### Test revenue

In [48]:
revenue = parser.extract_annual_metric(
    company_facts,
    "revenue"
)

revenue

Using SEC tag for revenue: RevenueFromContractWithCustomerExcludingAssessedTax

   fiscal_year      start        end  value_billions  growth_pct      filed
0         2017 2016-09-25 2017-09-30         229.234         NaN 2019-10-31
1         2018 2017-10-01 2018-09-29         265.595   15.861958 2020-10-30
2         2019 2018-09-30 2019-09-28         260.174   -2.041078 2021-10-29
3         2020 2019-09-29 2020-09-26         274.515    5.512080 2022-10-28
4         2021 2020-09-27 2021-09-25         365.817   33.259385 2023-11-03
5         2022 2021-09-26 2022-09-24         394.328    7.793788 2024-11-01
6         2023 2022-09-25 2023-09-30         383.285   -2.800461 2025-10-31
7         2024 2023-10-01 2024-09-28         391.035    2.021994 2025-10-31
8         2025 2024-09-29 2025-09-27         416.161    6.425512 2025-10-31

### Test Net Income

In [49]:
net_income = parser.extract_annual_metric(
    company_facts,
    "net_income"
)

net_income

Using SEC tag for net_income: NetIncomeLoss

    fiscal_year      start        end  value_billions  growth_pct      filed
0          2007 2006-10-01 2007-09-29           3.496         NaN 2009-10-27
1          2008 2007-09-30 2008-09-27           6.119   75.028604 2010-10-27
2          2009 2008-09-28 2009-09-26           8.235   34.580814 2011-10-26
3          2010 2009-09-27 2010-09-25          14.013   70.163934 2012-10-31
4          2011 2010-09-26 2011-09-24          25.922   84.985371 2013-10-30
5          2012 2011-09-25 2012-09-29          41.733   60.994522 2014-10-27
6          2013 2012-09-30 2013-09-28          37.037  -11.252486 2015-10-28
7          2014 2013-09-29 2014-09-27          39.510    6.677107 2016-10-26
8          2015 2014-09-28 2015-09-26          53.394   35.140471 2017-11-03
9          2016 2015-09-27 2016-09-24          45.687  -14.434206 2018-11-05
10         2017 2016-09-25 2017-09-30          48.351    5.830980 2019-10-31
11         2018 2017-10-01 2018-09-29          59.531   23.122583 2020-10-30
12         2019 2018-09-30 2019-09-28          55.256   -7.181133 2021-10-29
13         2020 2019-09-29 2020-09-26          57.411    3.900029 2022-10-28
14         2021 2020-09-27 2021-09-25          94.680   64.916131 2023-11-03
15         2022 2021-09-26 2022-09-24          99.803    5.410858 2024-11-01
16         2023 2022-09-25 2023-09-30          96.995   -2.813543 2025-10-31
17         2024 2023-10-01 2024-09-28          93.736   -3.359967 2025-10-31
18         2025 2024-09-29 2025-09-27         112.010   19.495178 2025-10-31

### Test Assets

In [50]:
assets = parser.extract_annual_metric(
    company_facts,
    "assets"
)

assets

Using SEC tag for assets: Assets

    fiscal_year        end  value_billions  growth_pct      filed
0          2008 2008-09-27          36.171         NaN 2010-10-27
1          2009 2009-09-26          47.501   31.323436 2011-10-26
2          2010 2010-09-25          75.183   58.276668 2011-10-26
3          2011 2011-09-24         116.371   54.783661 2012-10-31
4          2012 2012-09-29         176.064   51.295426 2013-10-30
5          2013 2013-09-28         207.000   17.570883 2014-10-27
6          2014 2014-09-27         231.839   11.999517 2015-10-28
7          2015 2015-09-26         290.345   25.235616 2016-10-26
8          2016 2016-09-24         321.686   10.794400 2017-11-03
9          2017 2017-09-30         375.319   16.672469 2018-11-05
10         2018 2018-09-29         365.725   -2.556226 2019-10-31
11         2019 2019-09-28         338.516   -7.439743 2020-10-30
12         2020 2020-09-26         323.888   -4.321214 2021-10-29
13         2021 2021-09-25         351.002    8.371412 2022-10-28
14         2022 2022-09-24         352.755    0.499427 2023-11-03
15         2023 2023-09-30         352.583   -0.048759 2024-11-01
16         2024 2024-09-28         364.980    3.516052 2025-10-31
17         2025 2025-09-27         359.241   -1.572415 2025-10-31

### Test liabilities

In [51]:
liabilities = parser.extract_annual_metric(
    company_facts,
    "liabilities"
)

liabilities

Using SEC tag for liabilities: Liabilities

    fiscal_year        end  value_billions  growth_pct      filed
0          2008 2008-09-27          18.542         NaN 2009-10-27
1          2009 2009-09-26          15.861  -14.459066 2010-10-27
2          2010 2010-09-25          27.392   72.700334 2011-10-26
3          2011 2011-09-24          39.756   45.137266 2012-10-31
4          2012 2012-09-29          57.854   45.522688 2013-10-30
5          2013 2013-09-28          83.451   44.244132 2014-10-27
6          2014 2014-09-27         120.292   44.146865 2015-10-28
7          2015 2015-09-26         170.990   42.145779 2016-10-26
8          2016 2016-09-24         193.437   13.127668 2017-11-03
9          2017 2017-09-30         241.272   24.728982 2018-11-05
10         2018 2018-09-29         258.578    7.172817 2019-10-31
11         2019 2019-09-28         248.028   -4.080007 2020-10-30
12         2020 2020-09-26         258.549    4.241860 2021-10-29
13         2021 2021-09-25         287.912   11.356841 2022-10-28
14         2022 2022-09-24         302.083    4.921990 2023-11-03
15         2023 2023-09-30         290.437   -3.855232 2024-11-01
16         2024 2024-09-28         308.030    6.057424 2025-10-31
17         2025 2025-09-27         285.508   -7.311625 2025-10-31

### Test Cash

In [52]:
cash = parser.extract_annual_metric(
    company_facts,
    "cash"
)

cash

Using SEC tag for cash: CashAndCashEquivalentsAtCarryingValue

    fiscal_year        end  value_billions  growth_pct      filed
0          2006 2006-09-30           6.392         NaN 2009-10-27
1          2007 2007-09-29           9.352   46.307885 2010-10-27
2          2008 2008-09-27          11.875   26.978186 2011-10-26
3          2009 2009-09-26           5.263  -55.680000 2012-10-31
4          2010 2010-09-25          11.261  113.965419 2013-10-30
5          2011 2011-09-24           9.815  -12.840778 2014-10-27
6          2012 2012-09-29          10.746    9.485481 2015-10-28
7          2013 2013-09-28          14.259   32.691234 2016-10-26
8          2014 2014-09-27          13.844   -2.910443 2017-11-03
9          2015 2015-09-26          21.120   52.557064 2018-11-05
10         2016 2016-09-24          20.484   -3.011364 2018-11-05
11         2017 2017-09-30          20.289   -0.951963 2018-11-05
12         2018 2018-09-29          25.913   27.719454 2019-10-31
13         2019 2019-09-28          48.844   88.492263 2020-10-30
14         2020 2020-09-26          38.016  -22.168537 2021-10-29
15         2021 2021-09-25          34.940   -8.091330 2022-10-28
16         2022 2022-09-24          23.646  -32.323984 2023-11-03
17         2023 2023-09-30          29.965   26.723336 2024-11-01
18         2024 2024-09-28          29.943   -0.073419 2025-10-31
19         2025 2025-09-27          35.934   20.008015 2025-10-31

### Test Operating Cash Flow

In [53]:
operating_cash_flow = parser.extract_annual_metric(
    company_facts,
    "operating_cash_flow"
)

operating_cash_flow

Using SEC tag for operating_cash_flow: NetCashProvidedByUsedInOperatingActivities

    fiscal_year      start        end  value_billions  growth_pct      filed
0          2007 2006-10-01 2007-09-29           5.470         NaN 2009-10-27
1          2008 2007-09-30 2008-09-27           9.596   75.429616 2010-10-27
2          2009 2008-09-28 2009-09-26          10.159    5.867028 2011-10-26
3          2010 2009-09-27 2010-09-25          18.595   83.039669 2012-10-31
4          2011 2010-09-26 2011-09-24          37.529  101.823071 2013-10-30
5          2012 2011-09-25 2012-09-29          50.856   35.511205 2013-10-30
6          2013 2012-09-30 2013-09-28          53.666    5.525405 2013-10-30
7          2015 2014-09-28 2015-09-26          81.266   51.429210 2017-11-03
8          2016 2015-09-27 2016-09-24          66.231  -18.500972 2018-11-05
9          2017 2016-09-25 2017-09-30          64.225   -3.028793 2019-10-31
10         2018 2017-10-01 2018-09-29          77.434   20.566757 2020-10-30
11         2019 2018-09-30 2019-09-28          69.391  -10.386910 2021-10-29
12         2020 2019-09-29 2020-09-26          80.674   16.260034 2022-10-28
13         2021 2020-09-27 2021-09-25         104.038   28.961004 2023-11-03
14         2022 2021-09-26 2022-09-24         122.151   17.409985 2024-11-01
15         2023 2022-09-25 2023-09-30         110.543   -9.502992 2025-10-31
16         2024 2023-10-01 2024-09-28         118.254    6.975566 2025-10-31
17         2025 2024-09-29 2025-09-27         111.482   -5.726656 2025-10-31

In [54]:
def prepare_metric(df, metric_name):
    """Prepare a metric DataFrame for merging."""

    result = df[
        ["fiscal_year", "value_billions"]
    ].copy()

    result = result.rename(
        columns={
            "value_billions": metric_name
        }
    )

    return result

In [55]:
revenue_clean = prepare_metric(
    revenue,
    "revenue"
)

net_income_clean = prepare_metric(
    net_income,
    "net_income"
)

assets_clean = prepare_metric(
    assets,
    "assets"
)

liabilities_clean = prepare_metric(
    liabilities,
    "liabilities"
)

cash_clean = prepare_metric(
    cash,
    "cash"
)

operating_cash_flow_clean = prepare_metric(
    operating_cash_flow,
    "operating_cash_flow"
)

In [56]:
financials = revenue_clean

In [57]:
financials = financials.merge(
    net_income_clean,
    on="fiscal_year",
    how="outer"
)

financials = financials.merge(
    assets_clean,
    on="fiscal_year",
    how="outer"
)

financials = financials.merge(
    liabilities_clean,
    on="fiscal_year",
    how="outer"
)

financials = financials.merge(
    cash_clean,
    on="fiscal_year",
    how="outer"
)

financials = financials.merge(
    operating_cash_flow_clean,
    on="fiscal_year",
    how="outer"
)

#### Sort by year

In [58]:
financials = financials.sort_values(
    "fiscal_year"
).reset_index(drop=True)

financials

,fiscal_year,revenue,net_income,assets,liabilities,cash,operating_cash_flow
0,2006,NaN,NaN,NaN,NaN,6.392,NaN
1,2007,NaN,3.496,NaN,NaN,9.352,5.470
2,2008,NaN,6.119,36.171,18.542,11.875,9.596
3,2009,NaN,8.235,47.501,15.861,5.263,10.159
4,2010,NaN,14.013,75.183,27.392,11.261,18.595
5,2011,NaN,25.922,116.371,39.756,9.815,37.529
6,2012,NaN,41.733,176.064,57.854,10.746,50.856
7,2013,NaN,37.037,207.000,83.451,14.259,53.666
8,2014,NaN,39.510,231.839,120.292,13.844,NaN
9,2015,NaN,53.394,290.345,170.990,21.120,81.266
10,2016,NaN,45.687,321.686,193.437,20.484,66.231
11,2017,229.234,48.351,375.319,241.272,20.289,64.225
12,2018,265.595,59.531,365.725,258.578,25.913,77.434
13,2019,260.174,55.256,338.516,248.028,48.844,69.391
14,2020,274.515,57.411,323.888,258.549,38.016,80.674
15,2021,365.817,94.680,351.002,287.912,34.940,104.038
16,2022,394.328,99.803,352.755,302.083,23.646,122.151
17,2023,383.285,96.995,352.583,290.437,29.965,110.543
18,2024,391.035,93.736,364.980,308.030,29.943,118.254
19,2025,416.161,112.010,359.241,285.508,35.934,111.482

In [59]:
financials[financials.isna().any(axis=1)]

,fiscal_year,revenue,net_income,assets,liabilities,cash,operating_cash_flow
0,2006,NaN,NaN,NaN,NaN,6.392,NaN
1,2007,NaN,3.496,NaN,NaN,9.352,5.470
2,2008,NaN,6.119,36.171,18.542,11.875,9.596
3,2009,NaN,8.235,47.501,15.861,5.263,10.159
4,2010,NaN,14.013,75.183,27.392,11.261,18.595
5,2011,NaN,25.922,116.371,39.756,9.815,37.529
6,2012,NaN,41.733,176.064,57.854,10.746,50.856
7,2013,NaN,37.037,207.000,83.451,14.259,53.666
8,2014,NaN,39.510,231.839,120.292,13.844,NaN
9,2015,NaN,53.394,290.345,170.990,21.120,81.266
10,2016,NaN,45.687,321.686,193.437,20.484,66.231

In [60]:
financials[financials["revenue"].notna()]

,fiscal_year,revenue,net_income,assets,liabilities,cash,operating_cash_flow
11,2017,229.234,48.351,375.319,241.272,20.289,64.225
12,2018,265.595,59.531,365.725,258.578,25.913,77.434
13,2019,260.174,55.256,338.516,248.028,48.844,69.391
14,2020,274.515,57.411,323.888,258.549,38.016,80.674
15,2021,365.817,94.680,351.002,287.912,34.940,104.038
16,2022,394.328,99.803,352.755,302.083,23.646,122.151
17,2023,383.285,96.995,352.583,290.437,29.965,110.543
18,2024,391.035,93.736,364.980,308.030,29.943,118.254
19,2025,416.161,112.010,359.241,285.508,35.934,111.482

In [61]:
financials.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fiscal_year          20 non-null     int32
 1   revenue              9 non-null      float64
 2   net_income           19 non-null     float64
 3   assets               18 non-null     float64
 4   liabilities          18 non-null     float64
 5   cash                 20 non-null     float64
 6   operating_cash_flow  18 non-null     float64
dtypes: float64(6), int32(1)
memory usage: 1.1 KB

In [62]:
financials.describe()

,fiscal_year,revenue,net_income,assets,liabilities,cash,operating_cash_flow
count,20.00000,9.000000,19.000000,18.000000,18.000000,20.000000,18.000000
mean,2015.50000,331.127111,52.258895,260.342722,178.220667,21.095050,66.197778
std,5.91608,72.157677,33.834766,120.406603,111.401432,12.087419,38.637773
min,2006.00000,229.234000,3.496000,36.171000,15.861000,5.263000,5.470000
25%,2010.75000,265.595000,31.479500,183.798000,64.253250,11.132250,40.860750
50%,2015.50000,365.817000,48.351000,322.787000,217.354500,20.386500,67.811000
75%,2020.25000,391.035000,76.633500,352.712000,278.775500,29.948500,98.345000
max,2025.00000,416.161000,112.010000,375.319000,308.030000,48.844000,122.151000

In [63]:
output_path = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "apple_financials.csv"
)

financials.to_csv(
    output_path,
    index=False
)

print(f"Saved to: {output_path}")

Saved to: c:\Users\Jobel Jose George\financial-copilot\data\processed\apple_financials.csv

In [64]:
complete_financials = financials.dropna().copy()

complete_financials

,fiscal_year,revenue,net_income,assets,liabilities,cash,operating_cash_flow
11,2017,229.234,48.351,375.319,241.272,20.289,64.225
12,2018,265.595,59.531,365.725,258.578,25.913,77.434
13,2019,260.174,55.256,338.516,248.028,48.844,69.391
14,2020,274.515,57.411,323.888,258.549,38.016,80.674
15,2021,365.817,94.680,351.002,287.912,34.940,104.038
16,2022,394.328,99.803,352.755,302.083,23.646,122.151
17,2023,383.285,96.995,352.583,290.437,29.965,110.543
18,2024,391.035,93.736,364.980,308.030,29.943,118.254
19,2025,416.161,112.010,359.241,285.508,35.934,111.482

In [65]:
complete_financials["fiscal_year"].tolist()

[2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]

In [66]:
complete_financials

,fiscal_year,revenue,net_income,assets,liabilities,cash,operating_cash_flow
11,2017,229.234,48.351,375.319,241.272,20.289,64.225
12,2018,265.595,59.531,365.725,258.578,25.913,77.434
13,2019,260.174,55.256,338.516,248.028,48.844,69.391
14,2020,274.515,57.411,323.888,258.549,38.016,80.674
15,2021,365.817,94.680,351.002,287.912,34.940,104.038
16,2022,394.328,99.803,352.755,302.083,23.646,122.151
17,2023,383.285,96.995,352.583,290.437,29.965,110.543
18,2024,391.035,93.736,364.980,308.030,29.943,118.254
19,2025,416.161,112.010,359.241,285.508,35.934,111.482

In [67]:
output_path = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "apple_financials.csv"
)

complete_financials.to_csv(
    output_path,
    index=False
)

print(f"Saved to: {output_path}")

Saved to: c:\Users\Jobel Jose George\financial-copilot\data\processed\apple_financials.csv

In [68]:
loaded_financials = pd.read_csv(
    output_path
)

loaded_financials

,fiscal_year,revenue,net_income,assets,liabilities,cash,operating_cash_flow
0,2017,229.234,48.351,375.319,241.272,20.289,64.225
1,2018,265.595,59.531,365.725,258.578,25.913,77.434
2,2019,260.174,55.256,338.516,248.028,48.844,69.391
3,2020,274.515,57.411,323.888,258.549,38.016,80.674
4,2021,365.817,94.680,351.002,287.912,34.940,104.038
5,2022,394.328,99.803,352.755,302.083,23.646,122.151
6,2023,383.285,96.995,352.583,290.437,29.965,110.543
7,2024,391.035,93.736,364.980,308.030,29.943,118.254
8,2025,416.161,112.010,359.241,285.508,35.934,111.482

In [69]:
loaded_financials.isna().sum()

fiscal_year            0
revenue                0
net_income             0
assets                 0
liabilities            0
cash                   0
operating_cash_flow    0
dtype: int64

### Financial Analyzer

In [70]:
analyzer = FinancialAnalyzer(complete_financials)

### Test 1 Revenue Growth

In [71]:
revenue_growth = analyzer.revenue_growth()

revenue_growth

   fiscal_year  revenue  revenue_growth_pct
0         2017  229.234                 NaN
1         2018  265.595           15.861958
2         2019  260.174           -2.041078
3         2020  274.515            5.512080
4         2021  365.817           33.259385
5         2022  394.328            7.793788
6         2023  383.285           -2.800461
7         2024  391.035            2.021994
8         2025  416.161            6.425512

###  Test 2 — Net Profit Margin

In [72]:
profit_margin = analyzer.net_profit_margin()

profit_margin

   fiscal_year  revenue  net_income  net_profit_margin_pct
0         2017  229.234      48.351              21.092421
1         2018  265.595      59.531              22.414202
2         2019  260.174      55.256              21.238095
3         2020  274.515      57.411              20.913611
4         2021  365.817      94.680              25.881793
5         2022  394.328      99.803              25.309641
6         2023  383.285      96.995              25.306234
7         2024  391.035      93.736              23.971256
8         2025  416.161     112.010              26.915064

### Test3 Operating Flow Margin

In [73]:
cash_flow_margin = analyzer.operating_cash_flow_margin()

cash_flow_margin

   fiscal_year  revenue  operating_cash_flow  operating_cash_flow_margin_pct
0         2017  229.234               64.225                       28.017223
1         2018  265.595               77.434                       29.154916
2         2019  260.174               69.391                       26.670997
3         2020  274.515               80.674                       29.387829
4         2021  365.817              104.038                       28.439903
5         2022  394.328              122.151                       30.977004
6         2023  383.285              110.543                       28.840941
7         2024  391.035              118.254                       30.241283
8         2025  416.161              111.482                       26.788190

In [74]:
asset_growth = analyzer.asset_growth()

asset_growth

   fiscal_year   assets  asset_growth_pct
0         2017  375.319               NaN
1         2018  365.725         -2.556226
2         2019  338.516         -7.439743
3         2020  323.888         -4.321214
4         2021  351.002          8.371412
5         2022  352.755          0.499427
6         2023  352.583         -0.048759
7         2024  364.980          3.516052
8         2025  359.241         -1.572415

In [75]:
revenue_cagr = analyzer.revenue_cagr()

print(f"Revenue CAGR: {revenue_cagr:.2f}%")

Revenue CAGR: 7.74%

In [76]:
income_cagr = analyzer.net_income_cagr()

print(f"Net Income CAGR: {income_cagr:.2f}%")

Net Income CAGR: 11.07%

In [77]:
liability_ratio = analyzer.liability_to_asset_ratio()

liability_ratio

   fiscal_year   assets  liabilities  liability_to_asset_pct
0         2017  375.319      241.272               64.284515
1         2018  365.725      258.578               70.702851
2         2019  338.516      248.028               73.269210
3         2020  323.888      258.549               79.826668
4         2021  351.002      287.912               82.025743
5         2022  352.755      302.083               85.635356
6         2023  352.583      290.437               82.374079
7         2024  364.980      308.030               84.396405
8         2025  359.241      285.508               79.475338

In [78]:
growth_comparison = analyzer.revenue_vs_income_growth()

growth_comparison

,fiscal_year,revenue,net_income,revenue_growth_pct,net_income_growth_pct,growth_difference_pct
0,2017,229.234,48.351,NaN,NaN,NaN
1,2018,265.595,59.531,15.861958,23.122583,7.260625
2,2019,260.174,55.256,-2.041078,-7.181133,-5.140055
3,2020,274.515,57.411,5.512080,3.900029,-1.612051
4,2021,365.817,94.680,33.259385,64.916131,31.656746
5,2022,394.328,99.803,7.793788,5.410858,-2.382930
6,2023,383.285,96.995,-2.800461,-2.813543,-0.013082
7,2024,391.035,93.736,2.021994,-3.359967,-5.381961
8,2025,416.161,112.010,6.425512,19.495178,13.069666

#### The SEC provides a JSON file containing companies and their CIKs. We'll download this once and use it as our lookup table.

In [80]:
import os
lookup = CompanyLookup(
    user_agent=os.getenv("SEC_USER_AGENT")
)

In [81]:
apple = lookup.find_company("Apple")

apple

{'name': 'Apple Inc.', 'ticker': 'AAPL', 'cik': '0000320193'}

In [82]:
microsoft = lookup.find_company("Microsoft")

microsoft

{'name': 'MICROSOFT CORP', 'ticker': 'MSFT', 'cik': '0000789019'}

In [84]:
amazon = lookup.find_company("Amazon")

amazon

{'name': 'AMAZON COM INC', 'ticker': 'AMZN', 'cik': '0001018724'}

In [85]:
tesla = lookup.find_company("Tesla")

tesla

{'name': 'Tesla, Inc.', 'ticker': 'TSLA', 'cik': '0001318605'}